### PR TITLE
Updating systems table color

### PR DESCRIPTION
**Pull request by Zina-Kamel**
This PR 
- updates the table colors in the Systems page to black 
- round numbers in the stats charts to 3 decimal places 
- updates the favicon and app name

favicon-update

### CODE REVIEW

**Comment by RolandSall** [comment]
`[updating systems table color](https://github.com/VIRA-LAU/fyp-interface/pull/13/commits/d3549f0afd36b8df1aaab042bd493153e1d56e15)`

Can you provide a screenshot @Zina-Kamel

**Comment by Zina-Kamel** [comment]
this change was mainly to change the font color to black (before the background color was updated to grey).

image

**Comment by RolandSall** [comment]
How would the table will look with black borders and white background ? @Zina-Kamel  if its better I would recommend the latter

**Comment by Zina-Kamel** [comment]
image
 I believe it is better

**Comment by RolandSall** [comment]
LGTM

**Comment by Zina-Kamel** [comment]
the update has been committed

**Pull request closed without merging**
